db:
  uri: mongodb://root:secret@127.0.0.1:27017
  name: mobile

redis:
  cluster:
    - host: 127.0.0.1
      port: 7000
    - host: 127.0.0.1
      port: 7001
    - host: 127.0.0.1
      port: 7002

elasticsearch:
  host: https://127.0.0.1:9200
  username: elastic
  password: 0dim3F8r0T0yNfu-e-PN

jwt:
  expiresIn: 7d

  oauth:
    google:
      clientId: 840630550127-0d4c4f03e9cb8jsoveemsrdvkas90dvr.apps.googleusercontent.com
      clientSecret: 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
      callbackUrl: http://localhost:3000/api/v1/auth/google/callback
    twitter:
      apiKey: yPIUvXnrpdNHyYnDCVQf5OhpR
      apiSecretKey: dmmtvWIPfnRugr1Bdhca59Ws9yuUFbmixZMVOadjImahLXX7sF
    kakao:
      appKey: 62a9ebd197313365db1613fafc0c7c35
    apple:
      audience: com.app.somnium
