version: '3'

services:
  mongo:
    restart: always
    network_mode: 'somnium-labs'
    container_name: mongo
    image: mongo:4.2.21
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'

  redis-1:
    restart: always
    container_name: redis-1
    image: redis
    command: >
      redis-server --port 7001 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip dev.somniumlabs.net 
      --cluster-announce-port 7001 
      --cluster-announce-bus-port 17001
    volumes:
      - ./data/redis-1:/data
    network_mode: host

  redis-2:
    restart: always
    container_name: redis-2
    image: redis
    command: >
      redis-server --port 7002 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip dev.somniumlabs.net 
      --cluster-announce-port 7002 
      --cluster-announce-bus-port 17002
    volumes:
      - ./data/redis-2:/data
    network_mode: host

  redis-3:
    restart: always
    container_name: redis-3
    image: redis
    command: >
      redis-server --port 7003 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip dev.somniumlabs.net 
      --cluster-announce-port 7003 
      --cluster-announce-bus-port 17003
    volumes:
      - ./data/redis-3:/data
    network_mode: host

  elasticsearch:
    restart: always
    network_mode: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - '9200:9200'
      - '9300:9300'

  kibana:
    restart: always
    network_mode: elastic
    image: docker.elastic.co/kibana/kibana:8.8.1
    container_name: kibana
    ports:
      - '5601:5601'

  keycloak:
    restart: always
    network_mode: somnium-labs
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8090:8080'
    command:
      - start-dev

  rabbitmq:
    restart: always
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5672:5672'
      - '15672:15672'

  envoy:
    restart: always
    image: envoyproxy/envoy:dev-8468cf26bf2facd576c549fd90cdb066f8204a10
    ports:
      - '9901:9901'
      - '10000:10000'
    # command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
