admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                # scheme_header_transformation:
                #   scheme_to_overwrite: https
                stat_prefix: ingress_http
                http2_protocol_options: {}
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ['*']
                      routes:
                        - match:
                            prefix: '/'
                          route:
                            cluster: grpc_backend
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: grpc_backend
      connect_timeout: 1s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      health_checks:
        - timeout: 1s
          interval: 10s
          no_traffic_interval: 1s # 클러스터에 라우팅된 트래픽이 전혀 없을 때 사용되는 간격
          unhealthy_threshold: 3
          healthy_threshold: 3
          grpc_health_check:
            service_name: grpc.health.v1.Health
      load_assignment:
        cluster_name: grpc_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 50000
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 50001
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 50002
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 50003

        # transport_socket:
        #   name: envoy.transport_sockets.tls
        #   typed_config:
        #     "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        #     sni: www.envoyproxy.io
