db:
  uri: mongodb://root:secret@127.0.0.1:27017
  name: mobile

oauth:
  google:
    clientId: 840630550127-0d4c4f03e9cb8jsoveemsrdvkas90dvr.apps.googleusercontent.com
    clientSecret: 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
    callbackUrl: http://localhost:3000/api/v1/auth/google/callback
  twitter:
    apiKey: yPIUvXnrpdNHyYnDCVQf5OhpR
    apiSecretKey: dmmtvWIPfnRugr1Bdhca59Ws9yuUFbmixZMVOadjImahLXX7sF
  kakao:
    appKey: a9c3a23589804b38712a300f26adcf02
