apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: somniumlabs-istiocontrolplane
spec:
  profile: default
  values:
    global:
      proxy: # envoy proxy settings
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        # nodeSelector 추가
        nodeSelector:
          istio: enabled # istio 라벨이 있는 노드에 배포
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
      # nodeSelector 추가
        nodeSelector:
          istio: enabled # istio 라벨이 있는 노드에 배포
    pilot: # istiod의 설정 부분
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        # nodeSelector 추가
        nodeSelector:
          istio: enabled # istio 라벨이 있는 노드에 배포
  meshConfig:
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY